<?php

namespace app\modules\backend\controllers;

use Yii;
use yii\web\Controller;
use app\modules\backend\models\Admin;
use app\models\Login;

/**
 * Default controller for the `backend` module
 */
class DefaultController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = 'normal';
        $this->enableCsrfValidation = false;
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * ajax登录
     */
    public function actionAjaxLogin(){
        if(!Yii::$app->user->isGuest) die('您已登录');
        $post = Yii::$app->request->post();
        if(!$post || empty($post)) die('提交数据为空');

        // todo 提交数据验证

        // 登录
        echo '<pre>';
        $login_object = new Login(2);
        $identity = $login_object::findIdentity(1);
        print_r($login_object::findIdentity(1));
        print_r($post);
        echo '</pre>';

        $login_res = Yii::$app->user->login($identity);

        echo '<pre>';
        print_r($login_res);
        echo '</pre>';
    }
}
