<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2017/10/19
 * Time:  23:21
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class AjaxController extends Controller
{

    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = 'mobile';
    }

    /**
     * 首页
     * @return string
     */
    public function actionIndex(){

        return $this->render('index');
    }

    /**
     * 列表页面
     * @return string
     */
    public function actionList(){

        return $this->render('list');
    }
}