<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2017/10/19
 * Time:  23:21
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class AjaxController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionList(){

    }
}