<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/12/8
 * Time: 11:26
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class ArrayController extends Controller
{
    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    public function actionTest(){
        if(array()){
            echo 'if(array()) is true';
        }else{
            echo 'if(array()) is false';
        }
        echo '<br/>';

        echo '<h3>用加号合并数组</h3>';
        $array1 = ['a'=>1,'b'=>2,'c'=>3];
        $array2 = ['d'=>4,'e'=>5,'f'=>6];
        echo '<pre>';
        print_r($array1+$array2);
        echo '</pre>';
        echo '<br/>';
        $array1 = [1,2,3];
        $array2 = [4,5,6];
        echo '<pre>';
        print_r($array1+$array2);
        echo '</pre>';
        echo '<br/>';

    }

    /**
     * 数组
     * 1. 数组的key值会有些强制转换：
     * 包含有合法整型值的字符串会被转换为整型。
     * 浮点数也会被转换为整型，意味着其小数部分会被舍去
     * 布尔值也会被转换成整型。
     * Null 会被转换为空字符串
     * 数组和对象不能被用为键名
     *
     * 2. 同键名的则使用最后一个值
     * 3. PHP 数组可以同时含有 integer 和 string 类型的键名，因为 PHP 实际并不区分索引数组和关联数组。
     * 4. 
     */
    public function actionIndex(){
        
    }

    /**
     * 数组转换1
     */
    public function actionName1(){
        $arr = [
            'name' => ['aaa','bbb'],
            'is_open' => [1,2],
            'type' => [2],
        ];
        $res = [];
        $keys = array_keys($arr);
        for($i=0;$i<count(current($arr));$i++){
            $values = array_column($arr, $i);
            $res[] = array_combine($keys, $values);
        }
        echo '<pre>';
        print_r($res);
        echo '</pre>';
    }

}