<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/12/8
 * Time: 11:26
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class ArrayController extends Controller
{
    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    public function actionTest(){
        if(array()){
            echo 'if(array()) is true';
        }else{
            echo 'if(array()) is false';
        }
        echo '<br/>';

        echo '<h3>用加号合并数组</h3>';
        $array1 = ['a'=>1,'b'=>2,'c'=>3];
        $array2 = ['d'=>4,'e'=>5,'f'=>6];
        echo '<pre>';
        print_r($array1+$array2);
        echo '</pre>';
        echo '<br/>';
        $array1 = [1,2,3];
        $array2 = [4,5,6];
        echo '<pre>';
        print_r($array1+$array2);
        echo '</pre>';
        echo '<br/>';

    }

}