<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2018/4/25
 * Time: 10:54
 * Desc: 认证
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\User;
use yii\filters\AccessControl;

class AuthenticationController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = 'normal';
        echo '用户认证页面<br/>';
    }

    public function actionIndex(){
        echo '首页，不需要登录<br/>';
    }

    public function actionAdd(){
        echo '新增页面，需要登录，没有登录提示登录或跳转至登录页面<br/>';
        if(Yii::$app->user->getIsGuest()){
            echo '<div class="alert alert-warning" role="alert">抱歉请先注册或登录！<a href="'.Yii::$app->user->loginUrl.'">去登录</a></div><br/>';
            Yii::$app->end();
        }

        $user_info = Yii::$app->user->identity;
        echo '欢迎你「'.$user_info['username'].'」，这里是新增页面';
    }

    public function actionUpdate(){
        echo '修改页面，特定用户可以修改，没有权限的跳转至首页或提示用户没有权限修改<br/>';
    }

    public function actionDel(){
        echo '删除页面，特定用户可以删除，没有权限的跳转至首页或提示用户没有权限修改<br/>';
    }

    public function actionLogin(){
        echo '登录页面<br/>';

        if(!Yii::$app->user->isGuest){
            echo '您已经登录成功，<a href="/authentication/index">去首页</a><br/>';
            Yii::$app->end();
        }

        if(Yii::$app->request->isPost){
            // 登录操作
            $data = Yii::$app->request->post();
            $user_identity = User::findIdentityByUsername($data['username']);
            if($user_identity){

                // 判断密码是否正确
                if($data['password'] == $user_identity['password']){
                    Yii::$app->user->login($user_identity, 60);
                    echo '<div class="alert alert-success" role="alert">登录成功<a href="/authentication/index">去首页</a></div><br/>';
                }else{
                    echo '<div class="alert alert-warning" role="alert">密码错误</div><br/>';
                }
                
            }else{
                echo '<div class="alert alert-warning" role="alert">该用户不存在</div><br/>';
            }
        }

        return $this->render('login');

    }

    public function actionUser(){
        echo '用户页面，需要登录，没有登录提示登录或跳转至登录页面<br/>';
        if(Yii::$app->user->getIsGuest()){
            echo '<div class="alert alert-warning" role="alert">抱歉请先注册或登录！<a href="'.Yii::$app->user->loginUrl.'">去登录</a></div><br/>';
            Yii::$app->end();
        }

        /** @var $user_identity User */
        $user_identity = Yii::$app->user->getIdentity();
        echo '欢迎你'.$user_identity->username.'，<a href="/authentication/logout">退出登录</a><br/>';

        echo '<pre>';
        print_r(Yii::$app->user->getIdentity());
        echo 'SESSION<br/>';
        print_r($_SESSION);
        echo 'COOKIE<br/>';
        print_r($_COOKIE);
        echo '</pre>';
    }

    public function actionLogout(){
        Yii::$app->user->logout();
        echo '<div class="alert alert-success" role="alert">登出成功<a href="/authentication/index">去首页</a></div><br/>';
    }


    public function actionPasswordHash(){
        $password = Yii::$app->request->get();
        $password_hash = password_hash($password['password'], PASSWORD_DEFAULT);
        echo '<pre>';
        print_r($password_hash); //123456 $2y$10$vSDbqs.HS7GRwUq1LVQj7uV3iEz9a1JW11P8suf42H0Lx4VbyN/wG
        echo '</pre>';
    }

    public function actionPasswordVerify(){
        $password = Yii::$app->request->get();
        if(password_verify($password['password'], $password['password_hash'])){
            echo '密码正确<br/>';
        }else{
            echo '密码错误<br/>';
        }
    }

}