<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2018/4/25
 * Time: 10:54
 * Desc: 认证
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class AuthenticationController extends Controller
{

    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        echo '用户认证页面<br/>';
    }

    public function actionIndex(){
        echo '首页，不需要登录<br/>';
    }

    public function actionAdd(){
        echo '新增页面，需要登录，没有登录提示登录或跳转至登录页面<br/>';
    }

    public function actionUpdate(){
        echo '修改页面，特定用户可以修改，没有权限的跳转至首页或提示用户没有权限修改<br/>';
    }

    public function actionDel(){
        echo '删除页面，特定用户可以删除，没有权限的跳转至首页或提示用户没有权限修改<br/>';
    }

}