<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2018/04/05
 * Time:  22:04
 * Desc:  boolean
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;


class BooleanController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 布尔值一般是用在流程控制中
     */
    public function actionIndex(){
        
    }

    

    
}

