<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2018/4/15
 * Time: 15:27
 * Desc: Callback / Callable 回调可调用的
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class CallbackController extends Controller
{
    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    /**
     * 1. 可以接受用户的自定义的回调函数作为参数，回调函数可以是普通函数，对象方法，静态方法
     * 2.
     */
    public function actionIndex(){

    }
}