<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/11/16
 * Time: 17:05
 * Desc: 事件
 */

namespace app\controllers;

use app\components\event\MessageEvent;
use Yii;
use yii\base\Controller;
use app\components\helper\MessageHelper;

class EventController extends Controller{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }


    public function actionSendMessage(){
        $message_helper = new MessageHelper();
        $message_event = new MessageEvent();

        // 附加事件处理器（绑定事件）
        $message_helper->on($message_helper::EVENT_MESSAGE_SEND,[$message_event, 'onMessageSend']);
        // 最后参数含义：是否将新的事件处理程序添加到现有处理程序列表的末尾。如果是false，新处理程序将在现有处理程序列表的开头插入。
        $message_helper->on($message_helper::EVENT_MESSAGE_SEND, [$message_event, 'onDealUserInfo'], ['user_info'=>'user info ...']);
        $message_helper->on($message_helper::EVENT_MESSAGE_SEND, [$message_event, 'onMessageLog'], ['data'=>'data ...'], false);

        $message_helper->send('trigger send time');
    }
}