<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/11/16
 * Time: 17:05
 * Desc: 事件
 */

namespace app\controllers;

use Yii;
use yii\base\Controller;

class EventController extends Controller{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }


}