<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2018/04/10
 * Time:  22:15
 * Desc:  float
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class FloatController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 浮点数
     *
     * 1. 浮点数的字长和平台相关，尽管通常最大值是 1.8e308 并具有 14 位十进制数字的精度（64 位 IEEE 格式）。
     * 2. 永远不要相信浮点数结果精确到了最后一位，也永远不要比较两个浮点数是否相等。如果确实需要更高的精度，应该使用任意精度数学函数或者 gmp 函数。
     * 3. 某些数学运算会产生一个由常量 NAN 所代表的结果。此结果代表着一个在浮点数运算中未定义或不可表述的值。由于 NAN 代表着任何不同值，不应拿 NAN 去和其它值进行比较，包括其自身。
     */
    public function actionIndex(){

    }

    
}