<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2018/7/13
 * Time: 16:00
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class HashController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function actionHashPassword(){
        $password = Yii::$app->request->get('password', '');
        echo password_hash($password, PASSWORD_DEFAULT);
    }

}