<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2017/11/28
 * Time:  22:46
 * Desc:  我是海归 - 数据统计
 */

namespace app\controllers;

use Yii;
use yii\web\controller;

class ImhgDataController extends Controller
{

      public function init()
      {
          parent::init(); // TODO: Change the autogenerated stub
          $this->layout = 'normal';
      }


      public function actionIndex(){
          return $this->render('index');
      }

}