<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/11/3
 * Time: 17:18
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class JavascriptController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = 'normal';
    }

    public function actionIndex(){
        $type = Yii::$app->request->get('', 'index');
        return $this->render($type);
    }

}