<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2017/11/07
 * Time:  22:01
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\controller;

class JqueryController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = 'normal';
    }

    public function actionIndex(){
        $type = Yii::$app->request->get('type','index');
        return $this->render($type);
    }
}


