<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/12/8
 * Time: 11:09
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class ObjectController extends Controller
{
    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    /**
     * 判断对象是否为空
     */
    public function actionObjectEmpty(){
        if((object) array()){
            echo 'if((object) array()) is true';
        }else{
            echo 'if((object) array()) is false';
        }
        echo '<br/>';
        if(empty((object) array())){
            echo 'if(empty(object) array()) is true';
        }else{
            echo 'if(empty(object) array()) is false';
        }
        echo '<br/>';
        if(json_encode((object) array()) == '{}'){
            echo 'if(json_encode((object) array()) == \'{}\') is true';
        }else{
            echo 'if(json_encode((object) array()) == \'{}\') is false';
        }
        echo '<br/>';
    }

    /**
     * 获取类的路径
     */
    public function actionClassName(){
        echo self::class;
    }

}