<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/10/25
 * Time: 13:51
 * Desc: 字符串处理测试
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class StringController extends Controller
{
    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    public function actionTest(){
        echo '"000"和0 ';
        if('000' == 0){
            echo '相等';
        }else{
            echo '不相等';
        }
        echo '<br/>';

    }
}