<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/12/14
 * Time: 16:52
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

use app\components\MyComponent;

class TestController extends Controller
{
    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    public function actionPhpInfo(){
        echo phpinfo();
    }

    public function actionDebugTest(){
        $a = 111;
        $a = 222;
        $a = 333;

        echo $a;
    }

    public function actionMyIp(){
        $agent = Yii::$app->request->getUserAgent();
        $host = Yii::$app->request->getUserHost();
        $ip = Yii::$app->request->getUserIp();

        echo $agent;
        echo '<br/>';
        echo $host;
        echo '<br/>';
        echo $ip;
        echo '<br/>';
    }

    /**
     * 组件的使用
     */
    public function actionComponent(){
        // 首先需要将组件加入组件配置列表
        // 方法一
        $component = new MyComponent(1, 2, ['prop1' => 3, 'prop2' => 4]);
        echo '<pre>';
        print_r($component);
        echo '</pre>';

        // 方法二
//        $component = \Yii::createObject([
//            'class' => MyComponent::className(),
//            'prop1' => 3,
//            'prop2' => 4,
//        ], [1, 2]);
//        echo '<pre>';
//        print_r($component);
//        echo '</pre>';

    }



}