<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/12/14
 * Time: 16:52
 * Desc:
 */

namespace app\controllers;

use app\models\Admin;
use app\models\User;
use Yii;
use yii\web\Controller;

use app\components\MyComponent;

class TestController extends Controller
{

    public function actions()
    {
        return array_merge(parent::actions(),[
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'view' => '/site/error.php'
            ],
        ]); // TODO: Change the autogenerated stub

    }

    public function actionHsz(){
        $this->layout = false;
        return $this->render('hsz');
    }

    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    public function actionPhpInfo(){
        echo phpinfo();
    }

    public function actionDebugTest(){
        $a = 111;
        $a = 222;
        $a = 333;

        echo $a;
    }

    public function actionMyIp(){
        $agent = Yii::$app->request->getUserAgent();
        $host = Yii::$app->request->getUserHost();
        $ip = Yii::$app->request->getUserIp();

        echo $agent;
        echo '<br/>';
        echo $host;
        echo '<br/>';
        echo $ip;
        echo '<br/>';
    }

    /**
     * 组件的使用
     */
    public function actionComponent(){
        // 首先需要将组件加入组件配置列表
        // 方法一
        $component = new MyComponent(1, 2, ['prop1' => 3, 'prop2' => 4]);
        echo '<pre>';
        print_r($component);
        echo '</pre>';

        // 方法二
//        $component = \Yii::createObject([
//            'class' => MyComponent::className(),
//            'prop1' => 3,
//            'prop2' => 4,
//        ], [1, 2]);
//        echo '<pre>';
//        print_r($component);
//        echo '</pre>';

    }

    public function actionAuthentication(){
        // 获取用户信息
        $identity = User::findIdentity(100);
        // 登录
        $login_res = Yii::$app->user->login($identity);
        echo '<pre>';
        print_r($login_res);
        print_r(Yii::$app->user->identity);
        echo '</pre>';
    }


    public function actionAuthOne(){
        // 获取访问用户信息
        $user = Yii::$app->user->identity;
        if(!$user) Yii::$app->end();

        echo '<pre>';
        print_r($_SESSION);
        print_r($_COOKIE);
        echo '</pre>';

        echo '欢迎您，'.$user->username;
    }

    public function actionAuthLoginOut(){
        // 登出
        $login_out_res = Yii::$app->user->logout();
        echo '<pre>';
        print_r($login_out_res);
        echo '</pre>';

        if($login_out_res){
            echo '<pre>';
            print_r(Yii::$app->user->isGuest);
            print_r(Yii::$app->user->identity);
            echo '</pre>';
            echo '登出成功';
        }else{
            echo '登出失败';
        }
    }


    public function actionTestModel(){
        $admin_model = new Admin();
        echo '<pre>';
        print_r($admin_model);
        echo '</pre>';
    }

}