<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/12/14
 * Time: 16:52
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class TestController extends Controller
{
    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    public function actionPhpInfo(){
        echo phpinfo();
    }

    public function actionDebugTest(){
        $a = 111;
        $a = 222;
        $a = 333;

        echo $a;
    }

}