<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2017/10/27
 * Time: 16:46
 * Desc:
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class TimeController extends Controller
{
    /**
     * 构造函数
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    /**
     * 返回按钮内容 例如：我要报名（剩余2个月截止）
     * @param $time int 报名截止时间
     * @return string
     */
    public function actionDiffTime($time){
        if(strtotime($time)){
            $time = strtotime($time);
        }
        $str = '报名已截止';
        if(!$time) return $str;
        $now_time = time();
        // 报名结束
        if($now_time >= $time) return $str;
        // 剩余时间
        $str = '我要报名';
        $diff_time = $time - $now_time;
        if($diff_time <= 3600){ // 小于一个小时均返回（剩余1小时截止）
            return $str.'（剩余1小时截止）';
        }else if($diff_time > 3600 && $diff_time <= 3600*24){ // 小时
            $hour = ceil($diff_time / 3600);
            return $str.'（剩余'.$hour.'小时截止）';
        }else if($diff_time > 3600*24 && $diff_time <= 3600*24*29){ // 天
            $day = ceil($diff_time / 3600 / 24);
            return $str.'（剩余'.$day.'天截止）';
        }else if($diff_time > 3600*24*29){ // 月
            $month = ceil($diff_time / 3600 / 24 / 30);
            return $str.'（剩余'.$month.'月截止）';
        }
    }

}