<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2018/06/06
 * Time:  20:26
 * Desc:  vue 初级学习
 */

namespace  app\controllers;

use Yii;
use yii\web\Controller;

class VueController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = 'normal';
        ini_set('display_errors', 'on');
        error_reporting(E_ALL);
    }

    public function actionIndex(){
        return $this->render('index');
    }
}