<?php
/**
 * User:  jiangm
 * Email: jmphper@foxmail.com
 * Date:  2019/01/12
 * Time:  21:03
 * Desc:  mirages teypecho 主题
 */

namespace app\modules\front\controllers;

use Yii;
use yii\web\Controller;

class MiragesController extends Controller
{

    public $layout = false;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

}