<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2018/3/14
 * Time: 11:20
 * Desc: 前台基础控制器
 */

namespace app\modules\front\components;

use yii\web\Controller;

class BaseController extends Controller
{
    // 构造函数
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        // 前台初始化操作
    }

    /**
     * 是否登录
     */
    public function isLogin(){

    }

}