<?php
/**
 * Author: jiangm
 * Email: jmphper@foxmail.com
 * Date: 2018/5/4
 * Time: 11:03
 * Desc: 后台控制器基础类
 */

namespace app\modules\backend\components;

use Yii;
use yii\web\Controller;

class AdminBaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = 'normal';

        // 必须要登录
        if(Yii::$app->user->isGuest) $this->redirect('default');
    }


}